ame: PHPUnit

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build:
    name: PHPUnit Tests (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4', '8.1']

    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.branch-name.outputs.current_branch }}

      - name: Setup PHP${{ matrix.php-versions }}, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          extensions: mbstring, xml, ctype, iconv, xdebug, imap, zip, ssh2
          coverage: xdebug #optional

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer global require phpunit/phpunit:^9

      - name: Run Tests (${{ matrix.php-versions }})
        run: $(composer config -g home)/vendor/bin/phpunit --verbose --stderr